# Generated by Django 4.1.7 on 2023-04-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
    ]
