# Generated by Django 4.1.7 on 2023-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_log_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='points',
            field=models.IntegerField(),
        ),
    ]
